import { connectToDatabase } from "./db";
import { User } from "@/models/User";
import { Address } from "@/models/Address";
import { Category } from "@/models/Category";
import { Product } from "@/models/Product";
import { Order } from "@/models/Order";
import { OrderItem } from "@/models/OrderItem";
import { Invoice } from "@/models/Invoice";
import { NotificationLog } from "@/models/NotificationLog";
import { Coupon } from "@/models/Coupon";
import { DeliveryRule } from "@/models/DeliveryRule";
import { createInvoiceForOrder } from "./invoice";
import { NotificationService } from "./notifications";
import { hashPassword } from "./auth";
import { logger } from "./logger";

export async function seedStoreData() {
  await connectToDatabase();

  logger.info("Seeding authentication test accounts & store catalog...");

  const defaultPassword = "Customer@123456";
  const adminPassword = "Admin@123456";
  const staffPassword = "Staff@123456";

  const customerHash = await hashPassword(defaultPassword);
  const adminHash = await hashPassword(adminPassword);
  const staffHash = await hashPassword(staffPassword);

  // 1. Seed Accounts
  let customer = await User.findOne({ email: "customer@figuresworld.com" });
  if (!customer) {
    customer = await User.create({
      name: "Monkey D. Luffy",
      email: "customer@figuresworld.com",
      passwordHash: customerHash,
      role: "CUSTOMER",
      phone: "+1 (555) 123-4567",
      isEmailVerified: true,
      isActive: true,
    });
  }

  let staff = await User.findOne({ email: "staff@figuresworld.com" });
  if (!staff) {
    staff = await User.create({
      name: "Trafalgar Law",
      email: "staff@figuresworld.com",
      passwordHash: staffHash,
      role: "STAFF",
      phone: "+1 (555) 234-5678",
      isEmailVerified: true,
      isActive: true,
    });
  }

  let admin = await User.findOne({ email: "admin@figuresworld.com" });
  if (!admin) {
    admin = await User.create({
      name: "Gol D. Roger",
      email: "admin@figuresworld.com",
      passwordHash: adminHash,
      role: "ADMIN",
      phone: "+1 (555) 999-0000",
      isEmailVerified: true,
      isActive: true,
    });
  }

  // 2. Default Address
  const existingAddress = await Address.findOne({ user: customer._id });
  if (!existingAddress) {
    const addr = await Address.create({
      user: customer._id,
      type: "shipping",
      fullName: "Monkey D. Luffy",
      phone: "+1 (555) 123-4567",
      streetLine1: "100 Thousand Sunny Deck",
      streetLine2: "Captain Quarters",
      city: "Grand Line",
      state: "East Blue",
      postalCode: "10001",
      country: "United States",
      isDefault: true,
    });
    customer.addresses = [addr._id];
    await customer.save();
  }

  // 3. Seed Categories
  const categoryDefs = [
    { name: "Anime Figures", slug: "anime-figures", description: "Scale figures and articulated models from popular anime series", displayOrder: 1 },
    { name: "Collectibles", slug: "collectibles", description: "Limited edition resin statues and collector busts", displayOrder: 2 },
    { name: "Accessories", slug: "accessories", description: "Display cases, LED risers, cleaning kits and figure accessories", displayOrder: 3 },
    { name: "Keychains", slug: "keychains", description: "Acrylic, metallic and rubber anime character keychains", displayOrder: 4 },
    { name: "Posters", slug: "posters", description: "High-definition collector wall scrolls and framed art prints", displayOrder: 5 },
    { name: "Manga", slug: "manga", description: "Original Japanese and translated manga volumes and box sets", displayOrder: 6 },
    { name: "Other Merchandise", slug: "other-merchandise", description: "Apparel, plushies, and gaming desk mats", displayOrder: 7 },
    {
      name: "Katanas & Replicas",
      slug: "katanas-replicas",
      description: "Collector display anime swords, scabbards, and metal weapons. Age restricted 18+.",
      displayOrder: 8,
      isRestricted: true,
      complianceRequirements: {
        minAge: 18,
        requiresIdVerification: true,
        disclaimerText: "Notice: Ornamental replica sword for display purposes only. Buyer must be 18 years or older and complies with local weapons regulations.",
        restrictedRegions: ["UK", "NY-NYC", "CA-SF"],
      },
    },
  ];

  const categoryMap: Record<string, any> = {};

  for (const cat of categoryDefs) {
    let existingCat = await Category.findOne({ slug: cat.slug });
    if (!existingCat) {
      existingCat = await Category.create(cat);
      logger.info(`Created category: ${cat.name}`);
    }
    categoryMap[cat.slug] = existingCat;
  }

  // 4. Seed Products (Action Figures, Katanas & Replicas, Collectibles with INR pricing)
  const productsDefs = [
    // --- DEMO COMPATIBILITY PRODUCT ---
    {
      name: "Anime Figure",
      slug: "anime-figure-collectible",
      description: "Signature premium collectible anime figure with articulated joints, high-definition sculpt, and collector display base.",
      price: 2499,
      stock: 25,
      category: categoryMap["anime-figures"]._id,
      brand: "Good Smile Company",
      series: "Original Shonen",
      sku: "AF-DEMO-2499",
      weight: 650,
      dimensions: { length: 18, width: 15, height: 26, unit: "cm" },
      images: [{ url: "https://images.unsplash.com/photo-1563089145-599997674d42?w=800", altText: "Anime Figure", isPrimary: true }],
      tags: ["scale-figure", "good-smile", "shonen"],
      status: "active" as const,
      isFeatured: true,
      isRestricted: false,
      ageRequirement: 0,
      ratingAverage: 4.9,
      reviewsCount: 42,
    },

    // --- ANIME ACTION FIGURES ---
    {
      name: "Monkey D. Luffy - Gear 5 'Sun God Nika' Scale Figure",
      slug: "luffy-gear-5-sun-god-scale-figure",
      description: "Stunning 1/7 scale figure of Monkey D. Luffy activating Gear 5 with cloud dynamic aura, pearlescent white hair sculpt, and translucent lightning effect base.",
      price: 5499,
      discountPrice: 4499,
      stock: 35,
      category: categoryMap["anime-figures"]._id,
      brand: "MegaHouse",
      series: "One Piece",
      sku: "OP-LFF-G5-001",
      weight: 850,
      dimensions: { length: 22, width: 20, height: 32, unit: "cm" },
      images: [{ url: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800", altText: "Luffy Gear 5 Figure", isPrimary: true }],
      tags: ["one-piece", "luffy", "gear-5", "nika", "scale-figure"],
      status: "active" as const,
      isFeatured: true,
      isRestricted: false,
      ageRequirement: 0,
      ratingAverage: 5.0,
      reviewsCount: 128,
    },
    {
      name: "Roronoa Zoro - Wano Oni Giri 3-Sword Battle Figure",
      slug: "roronoa-zoro-wano-oni-giri-figure",
      description: "Dynamic 1/8 scale action figure of Roronoa Zoro executing Rengoku Oni Giri in his Wano Kingdom green yukata with removable bandanna head sculpt and green aura slashes.",
      price: 4999,
      discountPrice: 3999,
      stock: 28,
      category: categoryMap["anime-figures"]._id,
      brand: "Tamashii Nations",
      series: "One Piece",
      sku: "OP-ZRO-WNO-003",
      weight: 790,
      dimensions: { length: 24, width: 20, height: 28, unit: "cm" },
      images: [{ url: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800", altText: "Roronoa Zoro Wano Figure", isPrimary: true }],
      tags: ["one-piece", "zoro", "wano", "action-figure"],
      status: "active" as const,
      isFeatured: true,
      isRestricted: false,
      ageRequirement: 0,
      ratingAverage: 4.9,
      reviewsCount: 95,
    },
    {
      name: "Tanjiro Kamado - Hinokami Kagura Dance of Fire God Scale Figure",
      slug: "tanjiro-kamado-hinokami-kagura",
      description: "Aniplex dynamic scale figure capturing the Dance of the Fire God with translucent flame vortex effects, Nichirin blade in motion, and detailed Demon Slayer Corps uniform folds.",
      price: 4299,
      discountPrice: 3499,
      stock: 30,
      category: categoryMap["anime-figures"]._id,
      brand: "Aniplex+",
      series: "Demon Slayer",
      sku: "DS-TNJ-HNK-003",
      weight: 720,
      dimensions: { length: 18, width: 18, height: 26, unit: "cm" },
      images: [{ url: "https://images.unsplash.com/photo-1563089145-599997674d42?w=800", altText: "Tanjiro Kagura Figure", isPrimary: true }],
      tags: ["demon-slayer", "tanjiro", "hinokami-kagura", "aniplex"],
      status: "active" as const,
      isFeatured: true,
      isRestricted: false,
      ageRequirement: 0,
      ratingAverage: 4.8,
      reviewsCount: 74,
    },
    {
      name: "Nezuko Kamado - Blood Demon Art Advancing Form Figure",
      slug: "nezuko-kamado-blood-demon-art-figure",
      description: "Awakened demon form Nezuko featuring creeping vine vein sculpts, dynamic single horn, surging pink pyrokinesis flames, and translucent crystalline base.",
      price: 3799,
      discountPrice: 2999,
      stock: 22,
      category: categoryMap["anime-figures"]._id,
      brand: "Good Smile Company",
      series: "Demon Slayer",
      sku: "DS-NZK-BDA-005",
      weight: 680,
      dimensions: { length: 17, width: 16, height: 24, unit: "cm" },
      images: [{ url: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800", altText: "Nezuko Kamado Figure", isPrimary: true }],
      tags: ["demon-slayer", "nezuko", "blood-demon-art", "pop-up-parade"],
      status: "active" as const,
      isFeatured: true,
      isRestricted: false,
      ageRequirement: 0,
      ratingAverage: 4.9,
      reviewsCount: 63,
    },
    {
      name: "Zenitsu Agatsuma - Thunderclap and Flash 1/8 Scale Figure",
      slug: "zenitsu-agatsuma-thunderclap-flash-figure",
      description: "Capturing Zenitsu in mid-dash unleashing First Form: Thunderclap and Flash Sixfold. Features crackling translucent yellow lightning effect pieces and battle-ready stance.",
      price: 3999,
      discountPrice: 3299,
      stock: 20,
      category: categoryMap["anime-figures"]._id,
      brand: "Kotobukiya",
      series: "Demon Slayer",
      sku: "DS-ZNT-TCF-006",
      weight: 710,
      dimensions: { length: 22, width: 18, height: 23, unit: "cm" },
      images: [{ url: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800", altText: "Zenitsu Thunder Figure", isPrimary: true }],
      tags: ["demon-slayer", "zenitsu", "thunder-breathing", "artfx-j"],
      status: "active" as const,
      isFeatured: true,
      isRestricted: false,
      ageRequirement: 0,
      ratingAverage: 4.7,
      reviewsCount: 51,
    },
    {
      name: "Gojo Satoru - Hollow Purple 1/7 Scale Master Statue",
      slug: "gojo-satoru-hollow-purple-statue",
      description: "Jujutsu Kaisen master Gojo Satoru casting Hollow Purple with floating blindfold, crystalline resin cursed energy foundation, and exchangeable unmasked head sculpt.",
      price: 7499,
      discountPrice: 5999,
      stock: 18,
      category: categoryMap["anime-figures"]._id,
      brand: "eStream SHIBUYA SCRAMBLE",
      series: "Jujutsu Kaisen",
      sku: "JJK-GJO-HLW-005",
      weight: 950,
      dimensions: { length: 24, width: 22, height: 30, unit: "cm" },
      images: [{ url: "https://images.unsplash.com/photo-1618336753974-aae8e04506aa?w=800", altText: "Gojo Satoru Statue", isPrimary: true }],
      tags: ["jujutsu-kaisen", "gojo", "hollow-purple", "statue"],
      status: "active" as const,
      isFeatured: true,
      isRestricted: false,
      ageRequirement: 0,
      ratingAverage: 5.0,
      reviewsCount: 112,
    },
    {
      name: "Ryomen Sukuna - Malevolent Shrine King of Curses Figure",
      slug: "ryomen-sukuna-malevolent-shrine-figure",
      description: "The King of Curses seated arrogantly atop the throne of skulls inside his Malevolent Shrine domain expansion, featuring intricate demonic curse tattoo markings and eerie red lighting base.",
      price: 5299,
      discountPrice: 4299,
      stock: 15,
      category: categoryMap["anime-figures"]._id,
      brand: "Kotobukiya",
      series: "Jujutsu Kaisen",
      sku: "JJK-SKN-MSH-008",
      weight: 1100,
      dimensions: { length: 25, width: 23, height: 28, unit: "cm" },
      images: [{ url: "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=800", altText: "Ryomen Sukuna Figure", isPrimary: true }],
      tags: ["jujutsu-kaisen", "sukuna", "curse", "malevolent-shrine"],
      status: "active" as const,
      isFeatured: true,
      isRestricted: false,
      ageRequirement: 0,
      ratingAverage: 4.9,
      reviewsCount: 88,
    },
    {
      name: "Megumi Fushiguro - Ten Shadows Divine Dog Action Figure",
      slug: "megumi-fushiguro-ten-shadows-figure",
      description: "Megumi forming the shadow hand sign to summon Divine Dog: Totality, with surging black shadow mist base and high-poseability joints.",
      price: 3499,
      discountPrice: 2799,
      stock: 24,
      category: categoryMap["anime-figures"]._id,
      brand: "Bandai Spirits",
      series: "Jujutsu Kaisen",
      sku: "JJK-MGM-TSH-009",
      weight: 600,
      dimensions: { length: 16, width: 14, height: 22, unit: "cm" },
      images: [{ url: "https://images.unsplash.com/photo-1569701813229-33284b643e3c?w=800", altText: "Megumi Fushiguro Figure", isPrimary: true }],
      tags: ["jujutsu-kaisen", "megumi", "ten-shadows"],
      status: "active" as const,
      isFeatured: false,
      isRestricted: false,
      ageRequirement: 0,
      ratingAverage: 4.8,
      reviewsCount: 39,
    },
    {
      name: "Naruto Uzumaki - Sage of Six Paths Rasenshuriken Figure",
      slug: "naruto-uzumaki-sage-six-paths-figure",
      description: "Naruto in Sage of Six Paths mode surrounded by floating Truth-Seeker Orbs, brandishing twin dual-element Rasenshurikens with glowing chakra paint.",
      price: 4499,
      discountPrice: 3699,
      stock: 26,
      category: categoryMap["anime-figures"]._id,
      brand: "MegaHouse G.E.M.",
      series: "Naruto Shippuden",
      sku: "NAR-NRT-SSP-010",
      weight: 820,
      dimensions: { length: 22, width: 20, height: 28, unit: "cm" },
      images: [{ url: "https://images.unsplash.com/photo-1608889175123-8ee362201f81?w=800", altText: "Naruto Sage of Six Paths Figure", isPrimary: true }],
      tags: ["naruto", "sage-of-six-paths", "kurama", "gem"],
      status: "active" as const,
      isFeatured: true,
      isRestricted: false,
      ageRequirement: 0,
      ratingAverage: 4.9,
      reviewsCount: 97,
    },
    {
      name: "Sasuke Uchiha - Susano'o Flame Chidori Edition Figure",
      slug: "sasuke-uchiha-susanoo-chidori-figure",
      description: "Sasuke wielding his Rinnegan and Eternal Mangekyo Sharingan, clad in the ribcage of purple Susano'o armor with high-voltage Chidori lightning.",
      price: 4699,
      discountPrice: 3799,
      stock: 22,
      category: categoryMap["anime-figures"]._id,
      brand: "Bandai Spirits",
      series: "Naruto Shippuden",
      sku: "NAR-SSK-SSN-011",
      weight: 890,
      dimensions: { length: 23, width: 21, height: 29, unit: "cm" },
      images: [{ url: "https://images.unsplash.com/photo-1608889825205-eebdb9fc5806?w=800", altText: "Sasuke Susanoo Figure", isPrimary: true }],
      tags: ["naruto", "sasuke", "susanoo", "chidori", "uchiha"],
      status: "active" as const,
      isFeatured: true,
      isRestricted: false,
      ageRequirement: 0,
      ratingAverage: 4.8,
      reviewsCount: 82,
    },
    {
      name: "Itachi Uchiha - Akatsuki Tsukuyomi Crow Diorama Figure",
      slug: "itachi-uchiha-akatsuki-tsukuyomi-figure",
      description: "Iconic Akatsuki cloak clad Itachi dissolving into a murder of shadow crows while activating the Tsukuyomi genjutsu under a blood-red moon display.",
      price: 5199,
      discountPrice: 4199,
      stock: 19,
      category: categoryMap["anime-figures"]._id,
      brand: "MegaHouse",
      series: "Naruto Shippuden",
      sku: "NAR-ITC-TSK-012",
      weight: 920,
      dimensions: { length: 24, width: 22, height: 30, unit: "cm" },
      images: [{ url: "https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=800", altText: "Itachi Uchiha Crow Figure", isPrimary: true }],
      tags: ["naruto", "itachi", "akatsuki", "tsukuyomi", "sharingan"],
      status: "active" as const,
      isFeatured: true,
      isRestricted: false,
      ageRequirement: 0,
      ratingAverage: 5.0,
      reviewsCount: 140,
    },
    {
      name: "Son Goku - Super Saiyan Ultra Instinct Master Stars Piece",
      slug: "son-goku-super-saiyan-ultra-instinct-figure",
      description: "Master Stars Piece 28cm figure of Son Goku in Autonomous Ultra Instinct with silver eyes, silver celestial aura shading, and shredded Gi details.",
      price: 3599,
      discountPrice: 2899,
      stock: 30,
      category: categoryMap["anime-figures"]._id,
      brand: "Banpresto",
      series: "Dragon Ball Super",
      sku: "DBZ-GKU-MUI-013",
      weight: 750,
      dimensions: { length: 18, width: 16, height: 28, unit: "cm" },
      images: [{ url: "https://images.unsplash.com/photo-1581833971358-2c8b550f87b3?w=800", altText: "Goku Ultra Instinct Figure", isPrimary: true }],
      tags: ["dragon-ball", "goku", "ultra-instinct", "banpresto"],
      status: "active" as const,
      isFeatured: false,
      isRestricted: false,
      ageRequirement: 0,
      ratingAverage: 4.8,
      reviewsCount: 76,
    },
    {
      name: "Vegeta - Super Saiyan Blue Final Flash Master Figure",
      slug: "vegeta-super-saiyan-blue-final-flash-figure",
      description: "The Saiyan Prince charging his devastating Final Flash beam with electric blue metallic hair finish and Saiyan battle armor texture.",
      price: 3499,
      discountPrice: 2799,
      stock: 25,
      category: categoryMap["anime-figures"]._id,
      brand: "Bandai Spirits",
      series: "Dragon Ball Super",
      sku: "DBZ-VGT-SSB-014",
      weight: 730,
      dimensions: { length: 17, width: 15, height: 26, unit: "cm" },
      images: [{ url: "https://images.unsplash.com/photo-1596727147705-61a532a659bd?w=800", altText: "Vegeta Final Flash Figure", isPrimary: true }],
      tags: ["dragon-ball", "vegeta", "ssb", "final-flash"],
      status: "active" as const,
      isFeatured: false,
      isRestricted: false,
      ageRequirement: 0,
      ratingAverage: 4.7,
      reviewsCount: 61,
    },
    {
      name: "Levi Ackerman - Beast Titan Slayer Dynamic Action Figure",
      slug: "levi-ackerman-beast-titan-slayer-figure",
      description: "Captain Levi spinning mid-air through giant forest trees with dual snap blades and omni-directional mobility gear smoke exhaust effects.",
      price: 4799,
      discountPrice: 3899,
      stock: 20,
      category: categoryMap["anime-figures"]._id,
      brand: "Kotobukiya ARTFX J",
      series: "Attack on Titan",
      sku: "AOT-LVI-BTS-015",
      weight: 840,
      dimensions: { length: 21, width: 19, height: 27, unit: "cm" },
      images: [{ url: "https://images.unsplash.com/photo-1546776310-eef45dd6d63c?w=800", altText: "Levi Ackerman Figure", isPrimary: true }],
      tags: ["attack-on-titan", "levi", "survey-corps", "artfx-j"],
      status: "active" as const,
      isFeatured: true,
      isRestricted: false,
      ageRequirement: 0,
      ratingAverage: 4.9,
      reviewsCount: 92,
    },
    {
      name: "Eren Yeager - Attack Titan Founding Shingeki Figure",
      slug: "eren-yeager-attack-titan-founding-figure",
      description: "Season 4 Yeagerist Eren Yeager tying his coat against the Shiganshina sunrise with hardened titan fist accessories and resolute gaze.",
      price: 4299,
      discountPrice: 3499,
      stock: 22,
      category: categoryMap["anime-figures"]._id,
      brand: "Good Smile Company",
      series: "Attack on Titan",
      sku: "AOT-ERN-ATK-016",
      weight: 790,
      dimensions: { length: 20, width: 18, height: 26, unit: "cm" },
      images: [{ url: "https://images.unsplash.com/photo-1535223289827-42f1e9919769?w=800", altText: "Eren Yeager Figure", isPrimary: true }],
      tags: ["attack-on-titan", "eren-yeager", "shingeki"],
      status: "active" as const,
      isFeatured: false,
      isRestricted: false,
      ageRequirement: 0,
      ratingAverage: 4.8,
      reviewsCount: 68,
    },
    {
      name: "Sung Jin-Woo - Shadow Monarch 'Arise' Scale Statue",
      slug: "sung-jin-woo-shadow-monarch-arise-statue",
      description: "The Shadow Monarch summoning Igris and Kaisel with glowing purple necrotic eyes, dual daggers Baruka's Dagger and Knight Killer, and smoke base.",
      price: 5999,
      discountPrice: 4999,
      stock: 16,
      category: categoryMap["anime-figures"]._id,
      brand: "Good Smile Company",
      series: "Solo Leveling",
      sku: "SLV-SJW-SHM-017",
      weight: 980,
      dimensions: { length: 24, width: 22, height: 30, unit: "cm" },
      images: [{ url: "https://images.unsplash.com/photo-1606663889134-b1dedb5ed8b7?w=800", altText: "Sung Jin-Woo Statue", isPrimary: true }],
      tags: ["solo-leveling", "sung-jin-woo", "shadow-monarch", "arise"],
      status: "active" as const,
      isFeatured: true,
      isRestricted: false,
      ageRequirement: 0,
      ratingAverage: 5.0,
      reviewsCount: 104,
    },
    {
      name: "Killua Zoldyck - Godspeed Lightning Transmuter Figure",
      slug: "killua-zoldyck-godspeed-lightning-figure",
      description: "Killua channeling high-voltage aura through his hair and extremities in Whirlwind Godspeed mode with translucent blue spark effects.",
      price: 3699,
      discountPrice: 2999,
      stock: 22,
      category: categoryMap["anime-figures"]._id,
      brand: "FREEing",
      series: "Hunter x Hunter",
      sku: "HXH-KLL-GDS-018",
      weight: 640,
      dimensions: { length: 18, width: 16, height: 24, unit: "cm" },
      images: [{ url: "https://images.unsplash.com/photo-1569701813229-33284b643e3c?w=800", altText: "Killua Zoldyck Figure", isPrimary: true }],
      tags: ["hunter-x-hunter", "killua", "godspeed"],
      status: "active" as const,
      isFeatured: false,
      isRestricted: false,
      ageRequirement: 0,
      ratingAverage: 4.8,
      reviewsCount: 45,
    },
    {
      name: "Saitama - One Punch Man Serious Punch Figure",
      slug: "saitama-one-punch-man-serious-punch-figure",
      description: "The Caped Baldy delivering a Serious Series Serious Punch that splits the atmosphere, with fluttering white cape and shattered earth display base.",
      price: 2999,
      discountPrice: 2399,
      stock: 28,
      category: categoryMap["anime-figures"]._id,
      brand: "Bandai Spirits",
      series: "One Punch Man",
      sku: "OPM-STM-SPN-019",
      weight: 620,
      dimensions: { length: 17, width: 15, height: 23, unit: "cm" },
      images: [{ url: "https://images.unsplash.com/photo-1581833971358-2c8b550f87b3?w=800", altText: "Saitama Serious Punch Figure", isPrimary: true }],
      tags: ["one-punch-man", "saitama", "serious-punch"],
      status: "active" as const,
      isFeatured: false,
      isRestricted: false,
      ageRequirement: 0,
      ratingAverage: 4.7,
      reviewsCount: 57,
    },

    // --- KATANAS & REPLICAS (18+ ORNAMENTAL SWORDS) ---
    {
      name: "Demon Slayer Tanjiro Kamado's Nichirin Black Blade Katana",
      slug: "demon-slayer-nichirin-katana-replica",
      description: "Authentic full-tang hand-forged 1045 high carbon steel replica of Tanjiro's pitch-black Nichirin blade. Comes with wheel-shaped black tsuba, Ray-skin wrapped tsuka, matching scabbard, and single-tier display stand. Unsharpened safety edge for adult collectors.",
      price: 4299,
      discountPrice: 3499,
      stock: 18,
      category: categoryMap["katanas-replicas"]._id,
      brand: "Hansei Blades",
      series: "Demon Slayer",
      sku: "WP-NCHR-TNJ-004",
      weight: 1250,
      dimensions: { length: 104, width: 8, height: 8, unit: "cm" },
      images: [{ url: "https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=800", altText: "Tanjiro Nichirin Katana", isPrimary: true }],
      tags: ["demon-slayer", "tanjiro", "nichirin", "katana", "replica"],
      status: "active" as const,
      isFeatured: true,
      isRestricted: true,
      ageRequirement: 18,
      shippingRestrictions: ["UK", "NY-NYC", "CA-SF"],
      ratingAverage: 4.9,
      reviewsCount: 89,
    },
    {
      name: "Kyojuro Rengoku's Flame Hashira Nichirin Katana",
      slug: "kyojuro-rengoku-flame-hashira-nichirin-katana",
      description: "The iconic blade of the Flame Hashira Kyojuro Rengoku featuring flame-shaped tsuba, vibrant two-tone scarlet flame hamon, kanji 'Destroy Demons' engraved on blade base, and white scabbard.",
      price: 4799,
      discountPrice: 3899,
      stock: 15,
      category: categoryMap["katanas-replicas"]._id,
      brand: "Hansei Blades",
      series: "Demon Slayer",
      sku: "WP-KTN-RNK-021",
      weight: 1300,
      dimensions: { length: 104, width: 8, height: 8, unit: "cm" },
      images: [{ url: "https://images.unsplash.com/photo-1601814933824-fd0b574dd592?w=800", altText: "Rengoku Flame Katana", isPrimary: true }],
      tags: ["demon-slayer", "rengoku", "flame-hashira", "katana", "replica"],
      status: "active" as const,
      isFeatured: true,
      isRestricted: true,
      ageRequirement: 18,
      shippingRestrictions: ["UK", "NY-NYC", "CA-SF"],
      ratingAverage: 5.0,
      reviewsCount: 115,
    },
    {
      name: "Zenitsu Agatsuma's Thunder Breathing Nichirin Katana",
      slug: "zenitsu-agatsuma-thunder-breathing-katana",
      description: "Full-scale unsharpened replica of Zenitsu's lightning Nichirin katana with golden lightning strike temper line along the blade, white wooden saya with gold triangle patterns, and brass circular tsuba.",
      price: 4399,
      discountPrice: 3599,
      stock: 16,
      category: categoryMap["katanas-replicas"]._id,
      brand: "Hansei Blades",
      series: "Demon Slayer",
      sku: "WP-KTN-ZNT-022",
      weight: 1220,
      dimensions: { length: 104, width: 8, height: 8, unit: "cm" },
      images: [{ url: "https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=800", altText: "Zenitsu Thunder Katana", isPrimary: true }],
      tags: ["demon-slayer", "zenitsu", "thunder", "katana", "replica"],
      status: "active" as const,
      isFeatured: true,
      isRestricted: true,
      ageRequirement: 18,
      shippingRestrictions: ["UK", "NY-NYC", "CA-SF"],
      ratingAverage: 4.8,
      reviewsCount: 78,
    },
    {
      name: "Inosuke Hashibira's Dual Serrated Beast Nichirin Katanas (Pair)",
      slug: "inosuke-hashibira-dual-serrated-katanas",
      description: "Complete pair (2 swords) of Inosuke's hand-chipped serrated Beast Breathing Nichirin swords with rugged cloth bandage handle wrap and custom twin horizontal tabletop display stand.",
      price: 6299,
      discountPrice: 4999,
      stock: 12,
      category: categoryMap["katanas-replicas"]._id,
      brand: "Hansei Blades",
      series: "Demon Slayer",
      sku: "WP-KTN-INS-023",
      weight: 2350,
      dimensions: { length: 104, width: 14, height: 8, unit: "cm" },
      images: [{ url: "https://images.unsplash.com/photo-1571757767119-68b8dbed8c97?w=800", altText: "Inosuke Dual Katanas", isPrimary: true }],
      tags: ["demon-slayer", "inosuke", "dual-swords", "serrated", "katana"],
      status: "active" as const,
      isFeatured: true,
      isRestricted: true,
      ageRequirement: 18,
      shippingRestrictions: ["UK", "NY-NYC", "CA-SF"],
      ratingAverage: 4.9,
      reviewsCount: 64,
    },
    {
      name: "Giyu Tomioka's Water Breathing Nichirin Katana",
      slug: "giyu-tomioka-water-breathing-katana",
      description: "Water Hashira Giyu Tomioka's unsharpened Nichirin katana featuring blue water ripple hamon temper line, burgundy hexagonal tsuba, and black lacquered wooden scabbard.",
      price: 4199,
      discountPrice: 3499,
      stock: 17,
      category: categoryMap["katanas-replicas"]._id,
      brand: "Hansei Blades",
      series: "Demon Slayer",
      sku: "WP-KTN-GYU-024",
      weight: 1200,
      dimensions: { length: 104, width: 8, height: 8, unit: "cm" },
      images: [{ url: "https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=800", altText: "Giyu Tomioka Katana", isPrimary: true }],
      tags: ["demon-slayer", "giyu", "water-breathing", "katana"],
      status: "active" as const,
      isFeatured: false,
      isRestricted: true,
      ageRequirement: 18,
      shippingRestrictions: ["UK", "NY-NYC", "CA-SF"],
      ratingAverage: 4.8,
      reviewsCount: 59,
    },
    {
      name: "Shinobu Kocho's Stinger Nichirin Katana",
      slug: "shinobu-kocho-stinger-nichirin-katana",
      description: "Insect Hashira Shinobu Kocho's distinct needle-point stinger katana featuring turquoise and gold butterfly tsuba, engraved 'Evil Demon Annihilation' kanji, and patterned white scabbard.",
      price: 4199,
      discountPrice: 3499,
      stock: 14,
      category: categoryMap["katanas-replicas"]._id,
      brand: "Hansei Blades",
      series: "Demon Slayer",
      sku: "WP-KTN-SHN-025",
      weight: 1100,
      dimensions: { length: 102, width: 8, height: 8, unit: "cm" },
      images: [{ url: "https://images.unsplash.com/photo-1601814933824-fd0b574dd592?w=800", altText: "Shinobu Kocho Katana", isPrimary: true }],
      tags: ["demon-slayer", "shinobu", "insect-hashira", "katana"],
      status: "active" as const,
      isFeatured: false,
      isRestricted: true,
      ageRequirement: 18,
      shippingRestrictions: ["UK", "NY-NYC", "CA-SF"],
      ratingAverage: 4.9,
      reviewsCount: 46,
    },
    {
      name: "Roronoa Zoro's Enma Master Katana (Oden's Blade)",
      slug: "roronoa-zoro-enma-master-katana",
      description: "Kozuki Oden's legendary Great Grade blade that cut Kaido, bequeathed to Zoro. Features royal purple lacquered saya adorned with golden flower crests, trefoil tsuba, and dark violet flame temper line.",
      price: 5199,
      discountPrice: 4199,
      stock: 20,
      category: categoryMap["katanas-replicas"]._id,
      brand: "Hansei Blades",
      series: "One Piece",
      sku: "WP-KTN-ENM-026",
      weight: 1280,
      dimensions: { length: 104, width: 8, height: 8, unit: "cm" },
      images: [{ url: "https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=800", altText: "Zoro Enma Katana", isPrimary: true }],
      tags: ["one-piece", "zoro", "enma", "katana", "replica"],
      status: "active" as const,
      isFeatured: true,
      isRestricted: true,
      ageRequirement: 18,
      shippingRestrictions: ["UK", "NY-NYC", "CA-SF"],
      ratingAverage: 5.0,
      reviewsCount: 132,
    },
    {
      name: "Roronoa Zoro's Wado Ichimonji Pure White Katana",
      slug: "roronoa-zoro-wado-ichimonji-katana",
      description: "Kuina's heirloom O Wazamono sword carried in Zoro's mouth. Pristine pearl-white scabbard, pure white ray-skin tsuka wrap, minimalist circular brass tsuba, and mirror-finished unsharpened carbon blade.",
      price: 4599,
      discountPrice: 3799,
      stock: 18,
      category: categoryMap["katanas-replicas"]._id,
      brand: "Hansei Blades",
      series: "One Piece",
      sku: "WP-KTN-WDO-027",
      weight: 1220,
      dimensions: { length: 104, width: 8, height: 8, unit: "cm" },
      images: [{ url: "https://images.unsplash.com/photo-1601814933824-fd0b574dd592?w=800", altText: "Wado Ichimonji Katana", isPrimary: true }],
      tags: ["one-piece", "zoro", "wado-ichimonji", "katana"],
      status: "active" as const,
      isFeatured: true,
      isRestricted: true,
      ageRequirement: 18,
      shippingRestrictions: ["UK", "NY-NYC", "CA-SF"],
      ratingAverage: 4.9,
      reviewsCount: 88,
    },
    {
      name: "Roronoa Zoro's Shusui Black Blade Katana",
      slug: "roronoa-zoro-shusui-black-blade-katana",
      description: "National Treasure of Wano wielded by Sword God Ryuma. Jet black blade with prominent red saw-tooth jagged hamon, circular flower tsuba, and black lacquered saya with circular red crests.",
      price: 4899,
      discountPrice: 3999,
      stock: 16,
      category: categoryMap["katanas-replicas"]._id,
      brand: "Hansei Blades",
      series: "One Piece",
      sku: "WP-KTN-SHS-028",
      weight: 1260,
      dimensions: { length: 104, width: 8, height: 8, unit: "cm" },
      images: [{ url: "https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=800", altText: "Zoro Shusui Katana", isPrimary: true }],
      tags: ["one-piece", "zoro", "shusui", "black-blade", "katana"],
      status: "active" as const,
      isFeatured: true,
      isRestricted: true,
      ageRequirement: 18,
      shippingRestrictions: ["UK", "NY-NYC", "CA-SF"],
      ratingAverage: 4.9,
      reviewsCount: 97,
    },
    {
      name: "Roronoa Zoro 3-Sword Complete Katana Set + Wooden Stand",
      slug: "roronoa-zoro-3-sword-complete-set",
      description: "The complete 3-sword arsenal of Roronoa Zoro: Enma (Purple), Wado Ichimonji (White), and Sandai Kitetsu (Red). Includes a complimentary 3-tier solid mahogany wood tabletop display stand.",
      price: 12999,
      discountPrice: 9999,
      stock: 10,
      category: categoryMap["katanas-replicas"]._id,
      brand: "Hansei Blades",
      series: "One Piece",
      sku: "WP-KTN-ZR3-029",
      weight: 4200,
      dimensions: { length: 106, width: 22, height: 26, unit: "cm" },
      images: [{ url: "https://images.unsplash.com/photo-1571757767119-68b8dbed8c97?w=800", altText: "Zoro 3-Sword Set", isPrimary: true }],
      tags: ["one-piece", "zoro", "3-sword-style", "katana-set", "collector"],
      status: "active" as const,
      isFeatured: true,
      isRestricted: true,
      ageRequirement: 18,
      shippingRestrictions: ["UK", "NY-NYC", "CA-SF"],
      ratingAverage: 5.0,
      reviewsCount: 146,
    },
    {
      name: "Trafalgar D. Water Law's Cursed Nodachi 'Kikoku'",
      slug: "trafalgar-law-cursed-nodachi-kikoku",
      description: "Surgeon of Death Law's massive 140cm two-handed cursed Nodachi featuring white faux-fur oblong crossguard, purple ito cord, and black wooden saya decorated with small white cross emblems.",
      price: 5499,
      discountPrice: 4499,
      stock: 14,
      category: categoryMap["katanas-replicas"]._id,
      brand: "Hansei Blades",
      series: "One Piece",
      sku: "WP-KTN-KKK-030",
      weight: 1550,
      dimensions: { length: 140, width: 9, height: 9, unit: "cm" },
      images: [{ url: "https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=800", altText: "Trafalgar Law Kikoku Sword", isPrimary: true }],
      tags: ["one-piece", "law", "kikoku", "nodachi", "katana"],
      status: "active" as const,
      isFeatured: false,
      isRestricted: true,
      ageRequirement: 18,
      shippingRestrictions: ["UK", "NY-NYC", "CA-SF"],
      ratingAverage: 4.8,
      reviewsCount: 67,
    },
    {
      name: "Sasuke Uchiha's Grass Cutter Kusanagi Straight Chokuto",
      slug: "sasuke-uchiha-kusanagi-chokuto-sword",
      description: "Sasuke's signature straight-blade chokuto sword from Naruto Shippuden with matte black natural wood scabbard, concealed hilt, Uchiha fan insignia, and dual-tone unsharpened blade.",
      price: 3999,
      discountPrice: 3299,
      stock: 20,
      category: categoryMap["katanas-replicas"]._id,
      brand: "Hansei Blades",
      series: "Naruto Shippuden",
      sku: "WP-KTN-KSN-031",
      weight: 1100,
      dimensions: { length: 100, width: 7, height: 6, unit: "cm" },
      images: [{ url: "https://images.unsplash.com/photo-1601814933824-fd0b574dd592?w=800", altText: "Sasuke Kusanagi Sword", isPrimary: true }],
      tags: ["naruto", "sasuke", "kusanagi", "chokuto", "sword"],
      status: "active" as const,
      isFeatured: false,
      isRestricted: true,
      ageRequirement: 18,
      shippingRestrictions: ["UK", "NY-NYC", "CA-SF"],
      ratingAverage: 4.7,
      reviewsCount: 53,
    },
    {
      name: "Ichigo Kurosaki's Tensa Zangetsu Bankai Katana",
      slug: "ichigo-kurosaki-tensa-zangetsu-katana",
      description: "The sleek Bankai form of Zangetsu featuring an all-black carbon steel blade, intricate Manji crossguard, black tsuka ito, and genuine black steel chain extending from the pommel.",
      price: 4799,
      discountPrice: 3899,
      stock: 16,
      category: categoryMap["katanas-replicas"]._id,
      brand: "Hansei Blades",
      series: "Bleach",
      sku: "WP-KTN-ZNG-032",
      weight: 1240,
      dimensions: { length: 104, width: 8, height: 8, unit: "cm" },
      images: [{ url: "https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=800", altText: "Ichigo Tensa Zangetsu Katana", isPrimary: true }],
      tags: ["bleach", "ichigo", "zangetsu", "bankai", "katana"],
      status: "active" as const,
      isFeatured: true,
      isRestricted: true,
      ageRequirement: 18,
      shippingRestrictions: ["UK", "NY-NYC", "CA-SF"],
      ratingAverage: 4.9,
      reviewsCount: 71,
    },

    // --- COLLECTIBLES, ACCESSORIES, KEYCHAINS, POSTERS ---
    {
      name: "Zoro Enma 3-Sword Style Battle Diorama",
      slug: "zoro-enma-3-sword-style-battle-diorama",
      description: "Highly detailed 1/6 scale statue featuring Roronoa Zoro unleashing green dragon Haki with Enma, Wado Ichimonji, and Sandai Kitetsu on a carved Wano cliff face base.",
      price: 9999,
      discountPrice: 7999,
      stock: 14,
      category: categoryMap["collectibles"]._id,
      brand: "Tsume Art",
      series: "One Piece",
      sku: "OP-ZRO-ENM-002",
      weight: 2400,
      dimensions: { length: 28, width: 25, height: 35, unit: "cm" },
      images: [{ url: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800", altText: "Zoro Diorama", isPrimary: true }],
      tags: ["one-piece", "zoro", "diorama", "statue", "resin"],
      status: "active" as const,
      isFeatured: true,
      isRestricted: false,
      ageRequirement: 0,
      ratingAverage: 5.0,
      reviewsCount: 84,
    },
    {
      name: "Solid Wood 3-Tier Katana Tabletop Display Stand",
      slug: "solid-wood-3-tier-katana-display-stand",
      description: "Premium solid hardwood 3-tier horizontal display rack with red velvet felt padding to protect katana scabbards from scratching. Fits all standard Japanese anime replica swords.",
      price: 1499,
      discountPrice: 999,
      stock: 45,
      category: categoryMap["accessories"]._id,
      brand: "Hansei",
      series: "Sword Accessories",
      sku: "ACC-STD-3TR-034",
      weight: 780,
      dimensions: { length: 38, width: 12, height: 30, unit: "cm" },
      images: [{ url: "https://images.unsplash.com/photo-1514539079130-25950c84af65?w=800", altText: "Katana Display Stand", isPrimary: true }],
      tags: ["stand", "accessories", "katana-display", "wood"],
      status: "active" as const,
      isFeatured: false,
      isRestricted: false,
      ageRequirement: 0,
      ratingAverage: 4.8,
      reviewsCount: 38,
    },
    {
      name: "Dust-Proof Acrylic Anime Figure LED Display Case",
      slug: "dust-proof-acrylic-figure-led-display-case",
      description: "High-transparency 98% optical acrylic showcase with built-in USB powered 3000K warm & 6000K daylight LED top/bottom lights to keep 1/7 scale figures dust-free.",
      price: 2499,
      discountPrice: 1899,
      stock: 35,
      category: categoryMap["accessories"]._id,
      brand: "Apex Displays",
      series: "Display Solutions",
      sku: "ACC-DSP-LED-035",
      weight: 1200,
      dimensions: { length: 25, width: 25, height: 35, unit: "cm" },
      images: [{ url: "https://images.unsplash.com/photo-1563089145-599997674d42?w=800", altText: "LED Display Case", isPrimary: true }],
      tags: ["display-case", "led", "acrylic", "accessories"],
      status: "active" as const,
      isFeatured: false,
      isRestricted: false,
      ageRequirement: 0,
      ratingAverage: 4.9,
      reviewsCount: 52,
    },
    {
      name: "Demon Slayer Metal Nichirin Katana Mini Keychain Set (5 Swords)",
      slug: "demon-slayer-metal-nichirin-keychain-set",
      description: "Collector set of 5 diecast zinc alloy 17cm mini Nichirin swords with functional sheaths and keyrings: Tanjiro, Rengoku, Zenitsu, Giyu, and Inosuke.",
      price: 999,
      discountPrice: 699,
      stock: 50,
      category: categoryMap["keychains"]._id,
      brand: "Bandai Spirits",
      series: "Demon Slayer",
      sku: "KEY-DS-NCH-036",
      weight: 350,
      dimensions: { length: 17, width: 8, height: 4, unit: "cm" },
      images: [{ url: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800", altText: "Nichirin Keychains", isPrimary: true }],
      tags: ["keychains", "demon-slayer", "metal", "mini-swords"],
      status: "active" as const,
      isFeatured: false,
      isRestricted: false,
      ageRequirement: 0,
      ratingAverage: 4.7,
      reviewsCount: 44,
    },
    {
      name: "One Piece Straw Hat Pirates Chibi Acrylic Keychain Bundle",
      slug: "one-piece-straw-hat-chibi-keychain-bundle",
      description: "Pack of 6 double-sided acrylic chibi keychains featuring Luffy, Zoro, Sanji, Nami, Chopper, and Law with holographic glitter finish and stainless steel carabiners.",
      price: 799,
      discountPrice: 499,
      stock: 60,
      category: categoryMap["keychains"]._id,
      brand: "Toei Animation",
      series: "One Piece",
      sku: "KEY-OP-CHB-037",
      weight: 220,
      dimensions: { length: 12, width: 8, height: 2, unit: "cm" },
      images: [{ url: "https://images.unsplash.com/photo-1569701813229-33284b643e3c?w=800", altText: "One Piece Keychains", isPrimary: true }],
      tags: ["keychains", "one-piece", "chibi", "acrylic"],
      status: "active" as const,
      isFeatured: false,
      isRestricted: false,
      ageRequirement: 0,
      ratingAverage: 4.8,
      reviewsCount: 36,
    },
    {
      name: "Demon Slayer Infinity Castle Metallic Foil Collector Poster (A2)",
      slug: "demon-slayer-infinity-castle-foil-poster",
      description: "Official A2 size (420 x 594 mm) heavy 300 GSM art print featuring the Upper Rank Demons and Hashira inside the Infinity Castle with selective metallic gold foil embossing.",
      price: 1199,
      discountPrice: 799,
      stock: 40,
      category: categoryMap["posters"]._id,
      brand: "Ufotable Official",
      series: "Demon Slayer",
      sku: "PST-DS-INF-038",
      weight: 180,
      dimensions: { length: 60, width: 42, height: 1, unit: "cm" },
      images: [{ url: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=800", altText: "Demon Slayer Foil Poster", isPrimary: true }],
      tags: ["posters", "demon-slayer", "infinity-castle", "wall-art"],
      status: "active" as const,
      isFeatured: false,
      isRestricted: false,
      ageRequirement: 0,
      ratingAverage: 4.9,
      reviewsCount: 29,
    },
    {
      name: "One Piece Egghead Arc Emperors Canvas Wall Scroll Art",
      slug: "one-piece-egghead-arc-emperors-wall-scroll",
      description: "Durable silk-finish canvas wall scroll depicting the Four Emperors of the Sea (Luffy, Shanks, Blackbeard, Buggy) with lightweight aluminum hanging rods.",
      price: 1299,
      discountPrice: 899,
      stock: 35,
      category: categoryMap["posters"]._id,
      brand: "Toei Animation",
      series: "One Piece",
      sku: "PST-OP-EGG-039",
      weight: 290,
      dimensions: { length: 90, width: 60, height: 2, unit: "cm" },
      images: [{ url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800", altText: "One Piece Canvas Wall Scroll", isPrimary: true }],
      tags: ["posters", "one-piece", "wall-scroll", "canvas", "emperors"],
      status: "active" as const,
      isFeatured: false,
      isRestricted: false,
      ageRequirement: 0,
      ratingAverage: 4.9,
      reviewsCount: 31,
    },
  ];

  for (const prod of productsDefs) {
    const existingProd = await Product.findOne({ sku: prod.sku });
    if (!existingProd) {
      await Product.create(prod);
      logger.info(`Created catalog product: ${prod.name} (₹${prod.price})`);
    } else {
      existingProd.name = prod.name;
      existingProd.title = prod.name;
      existingProd.price = prod.price;
      existingProd.discountPrice = prod.discountPrice !== undefined ? prod.discountPrice : null;
      existingProd.description = prod.description;
      existingProd.brand = prod.brand;
      if ((prod as any).series) existingProd.series = (prod as any).series;
      if (prod.category) existingProd.category = prod.category;
      if (prod.images && prod.images.length > 0) existingProd.images = prod.images as any;
      if ((prod as any).tags) existingProd.tags = (prod as any).tags;
      if (prod.dimensions) existingProd.dimensions = prod.dimensions as any;
      if (prod.weight) existingProd.weight = prod.weight;
      if ((prod as any).ratingAverage) existingProd.ratingAverage = (prod as any).ratingAverage;
      if ((prod as any).reviewsCount) existingProd.reviewsCount = (prod as any).reviewsCount;
      existingProd.isRestricted = !!prod.isRestricted;
      existingProd.ageRequirement = prod.ageRequirement || 0;
      if (prod.shippingRestrictions) existingProd.shippingRestrictions = prod.shippingRestrictions;
      existingProd.stock = prod.stock;
      await existingProd.save();
      logger.info(`Updated catalog product with INR pricing: ${prod.name} (₹${prod.price})`);
    }
  }

  // 5. Seed Reference Order #KF100001 for Sprint 9 Admin Order Inspection
  let kfOrder = await Order.findOne({ orderNumber: "KF100001" });
  if (!kfOrder) {
    const defaultAddr = await Address.findOne({ user: customer._id }) || await Address.findOne();
    const demoProd = await Product.findOne({ sku: "AF-DEMO-2499" });

    if (defaultAddr && demoProd) {
      kfOrder = await Order.create({
        orderNumber: "KF100001",
        customer: customer._id,
        customerEmail: customer.email,
        items: [],
        pricing: {
          subtotal: 4998,
          discountTotal: 0,
          taxTotal: 0,
          shippingFee: 100,
          grandTotal: 5098,
          currency: "INR",
        },
        shippingAddress: defaultAddr._id,
        paymentMethod: "UPI",
        paymentStatus: "PAID",
        orderStatus: "PROCESSING",
        paymentDetails: {
          merchantUpiId: "figuresworld@icici",
          customerUpiId: "luffy@okicici",
          transactionRef: "426189304721",
          upiApp: "Google Pay",
          submittedAt: new Date(Date.now() - 7200000),
          verifiedAt: new Date(Date.now() - 3600000),
          verifiedBy: admin._id,
          verificationNotes: "Verified via ICICI corporate banking",
        },
        shipmentDetails: {
          courier: "Blue Dart Express",
          trackingNumber: "BD-KF100001",
          trackingUrl: "https://www.bluedart.com/tracking?track=BD-KF100001",
          dispatchedAt: new Date(),
          shippingNotes: "Signature collector anime figure. Fragile handling required.",
        },
        statusHistory: [
          { status: "PENDING_PAYMENT", changedAt: new Date(Date.now() - 7200000), notes: "Order checkout placed" },
          { status: "PAYMENT_REVIEW", changedAt: new Date(Date.now() - 5400000), notes: "Customer submitted UPI UTR 426189304721" },
          { status: "CONFIRMED", changedAt: new Date(Date.now() - 3600000), notes: "Admin confirmed payment" },
          { status: "PROCESSING", changedAt: new Date(Date.now() - 1800000), notes: "Warehouse picking and packaging" },
        ],
        notes: "Priority delivery requested by customer",
        placedAt: new Date(Date.now() - 7200000),
      });

      const orderItem = await OrderItem.create({
        order: kfOrder._id,
        product: demoProd._id,
        productTitle: demoProd.name,
        productSku: demoProd.sku,
        productImage: demoProd.images?.[0]?.url || "https://images.unsplash.com/photo-1563089145-599997674d42?w=800",
        unitPrice: 2499,
        quantity: 2,
        subtotal: 4998,
        discountAmount: 0,
        total: 4998,
      });

      kfOrder.items = [orderItem._id];
      await kfOrder.save();
      logger.info("Seeded reference order: #KF100001");

      // Generate invoice for #KF100001
      try {
        const existingInv = await Invoice.findOne({ order: kfOrder._id });
        if (!existingInv) {
          await createInvoiceForOrder(kfOrder.orderNumber);
          logger.info("Seeded invoice for reference order #KF100001");
        }
      } catch (invErr) {
        logger.error("Error seeding invoice for #KF100001:", { error: String(invErr) });
      }
    }
  }

  // Ensure WhatsApp notifications exist for reference order #KF100001
  try {
    const kf = await Order.findOne({ orderNumber: "KF100001" });
    if (kf) {
      const existingNotifs = await NotificationLog.countDocuments({ orderNumber: "KF100001" });
      if (existingNotifs === 0) {
        await NotificationService.sendOrderConfirmation(kf);
        await NotificationService.sendPaymentConfirmation(kf);
        await NotificationService.sendInvoice(kf);
        await NotificationService.sendDispatchDetails(kf);
        logger.info("Seeded WhatsApp notifications for reference order #KF100001");
      }
    }
  } catch (notifErr) {
    logger.error("Error seeding WhatsApp notifications for #KF100001:", { error: String(notifErr) });
  }

  // 5. Seed Promotional Coupons
  try {
    const existingCoupons = await Coupon.countDocuments({});
    if (existingCoupons === 0) {
      await Coupon.create({
        code: "WELCOME10",
        description: "10% off on your first anime collectible order",
        discountType: "percentage",
        discountValue: 10,
        minimumOrderValue: 999,
        maximumDiscountAmount: 500,
        validFrom: new Date(Date.now() - 30 * 24 * 3600 * 1000),
        validUntil: new Date("2027-12-31T23:59:59Z"),
        usageLimit: 500,
        usedCount: 24,
        isActive: true,
      });

      await Coupon.create({
        code: "ANIME500",
        description: "Flat ₹500 instant discount on premium figures",
        discountType: "fixed",
        discountValue: 500,
        minimumOrderValue: 2499,
        validFrom: new Date(Date.now() - 15 * 24 * 3600 * 1000),
        validUntil: new Date("2027-12-31T23:59:59Z"),
        usageLimit: 200,
        usedCount: 42,
        isActive: true,
      });

      await Coupon.create({
        code: "KATANA15",
        description: "15% off on collector replica blades and katanas",
        discountType: "percentage",
        discountValue: 15,
        minimumOrderValue: 1500,
        maximumDiscountAmount: 1000,
        validFrom: new Date(Date.now() - 7 * 24 * 3600 * 1000),
        validUntil: new Date("2027-12-31T23:59:59Z"),
        usageLimit: 100,
        usedCount: 8,
        isActive: true,
      });

      await Coupon.create({
        code: "EXPIRED20",
        description: "Seasonal 20% discount (Past campaign)",
        discountType: "percentage",
        discountValue: 20,
        minimumOrderValue: 1000,
        maximumDiscountAmount: 400,
        validFrom: new Date(Date.now() - 90 * 24 * 3600 * 1000),
        validUntil: new Date(Date.now() - 15 * 24 * 3600 * 1000),
        usageLimit: 100,
        usedCount: 100,
        isActive: false,
      });

      logger.info("Seeded sample promotional coupons: WELCOME10, ANIME500, KATANA15, EXPIRED20");
    }
  } catch (couponErr) {
    logger.error("Error seeding coupons:", { error: String(couponErr) });
  }

  // Ensure default baseline delivery rates (isFreeShippingActive = false)
  try {
    const deliveryRule = await DeliveryRule.findOne({});
    if (deliveryRule) {
      deliveryRule.isFreeShippingActive = false;
      await deliveryRule.save();
    }
  } catch (deliveryErr) {
    logger.error("Error resetting delivery rule in seed:", { error: String(deliveryErr) });
  }

  return {
    categoriesCount: categoryDefs.length,
    productsCount: productsDefs.length,
    accounts: {
      customer: customer.email,
      staff: staff.email,
      admin: admin.email,
    },
  };
}

export const seedAuthData = seedStoreData;
